/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package base_gui;

/**
 *
 * @author exor_p
 */
public class main_menu extends javax.swing.JFrame {

    /**
     * Creates new form main_menu
     */
    public main_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pasarcaixa = new javax.swing.JButton();
        llistats = new javax.swing.JButton();
        sortir = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 197, 188));
        jLabel1.setText("Menú Principal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 320, 70));

        pasarcaixa.setBackground(new java.awt.Color(14, 133, 251));
        pasarcaixa.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        pasarcaixa.setForeground(new java.awt.Color(16, 243, 245));
        pasarcaixa.setText("Pasar per caixa");
        pasarcaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasarcaixaActionPerformed(evt);
            }
        });
        getContentPane().add(pasarcaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 270, -1));

        llistats.setBackground(new java.awt.Color(14, 133, 251));
        llistats.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        llistats.setForeground(new java.awt.Color(16, 243, 245));
        llistats.setText("Generar llistats");
        llistats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                llistatsActionPerformed(evt);
            }
        });
        getContentPane().add(llistats, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 270, -1));

        sortir.setBackground(new java.awt.Color(14, 133, 251));
        sortir.setFont(new java.awt.Font("DialogInput", 0, 18)); // NOI18N
        sortir.setForeground(new java.awt.Color(16, 243, 245));
        sortir.setText("Sortir");
        sortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortirActionPerformed(evt);
            }
        });
        getContentPane().add(sortir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 270, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1247, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pasarcaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasarcaixaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasarcaixaActionPerformed

    private void llistatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_llistatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_llistatsActionPerformed

    private void sortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sortirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton llistats;
    private javax.swing.JButton pasarcaixa;
    private javax.swing.JButton sortir;
    // End of variables declaration//GEN-END:variables
}
